version: '3.7'

volumes:
  celtra_db:
    external: true

services:
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:2.4.4-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
      MYSQL_DATABASE: ads
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - celtra_db:/var/lib/mysql

  impressions-gen:
    build: services/impression-tcp-gen
    restart: always

  impressions-agg:
    build: services/impression-agg
    restart: always
    depends_on:
      - impressions-gen
