version: '3.7'

volumes:
  celtra_db:
    external: true

services:
  spark-master:
    image: bde2020/spark-master:2.4.4-hadoop2.7
    restart: always
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    build: services/spark-worker
    restart: always
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Password123!
      - MYSQL_DATABASE=ads
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/0_schema.sql:ro
      - ./data.sql:/docker-entrypoint-initdb.d/1_data.sql:ro
      - celtra_db:/var/lib/mysql

  impressions-api:
    build: services/impression-rest-api
    restart: always
    depends_on:
      - db
    ports:
      - 8080:5000

  impressions-gen:
    build: services/impression-tcp-gen
    restart: always

  impressions-agg:
    build: services/impression-agg
    restart: always
    depends_on:
      - spark-worker
      - impressions-gen
